### ISSUE TITLE
Kurgu

### ISSUE THREAD

**Issue by fatihmeh** [fatihmeh/Choose-Your-Operating-System#1]
Buradan yürüyebiliriz.

Edit: Bulunan  resimi kaldırdım.

**Comment by fatihmeh** [comment]
@obdegirmenci 
![image](https://user-images.githubusercontent.com/34105974/59601239-1e918880-910c-11e9-8065-202d0897247a.png)
Şöyle bir şey yaptım. Bu kadar basit olması aklımda yoktu ama gayet net bir şey ortaya çıktı :d

**Comment by fatihmeh** [comment]
Evet-hayır cevapları olayı biraz kısıtlıyor gibi. Şunu da örnek alabiliriz

https://i2.wp.com/www.hdt-project.org/wp-content/uploads/2017/06/info2.jpg

**Comment by obdegirmenci** [comment]
İlk olanı basit de diğerinde geriye dönme olayı var. Ama zaten istisnalar hariç geneli mantıksal olarak evet-hayır şeklinde geçiyor içinde ne yazarsa yazsın kompüterimize böyle anlatacağız. :D

**Comment by fatihmeh** [comment]
Şimdilik bunun https://github.com/fatihmeh/Choose-your-OS/issues/1#issuecomment-502644356 üzerinden gidelim. Ortaya bir şeyler çıkınca düzeltmeler yaparız. Tasarım için bir issue açtım #5

**Comment by fatihmeh** [comment]
Kurgu için şimdilik böyle devam ettiğimiz için bunu kapatıyorum.
