### ISSUE TITLE
Çeviriler

### ISSUE THREAD

**Issue by obdegirmenci** [fatihmeh/Choose-Your-Operating-System#11]
İngilizce çeviri eksik. Tam bilgim yok. Bazılarını yazdım fakat emin değilim.

**Comment by onrdrsy** [comment]
@fatihmeh,
Türkçe hitap için kurumsal dil mi kullanılmalı yoksa senli benli mi?

**Comment by fatihmeh** [comment]
> 
> 
> @fatihmeh,
> Türkçe hitap için kurumsal dil mi kullanılmalı yoksa senli benli mi?

Samimi olsun bence

**Comment by fatihmeh** [comment]
#12 ile İngilizce çevirileri güncellendi
Uygunsa kapatalım bu issue'yu @obdegirmenci

**Comment by obdegirmenci** [comment]
> 
> 
> #12 ile İngilizce çevirileri güncellendi
> Uygunsa kapatalım bu issue'yu @obdegirmenci

Tamamdır. Türkçe'de var mı bir sıkıntı?

**Comment by fatihmeh** [comment]
> 
> 
> > #12 ile İngilizce çevirileri güncellendi
> > Uygunsa kapatalım bu issue'yu @obdegirmenci
> 
> Tamamdır. Türkçe'de var mı bir sıkıntı?

Yeterli bence. @onrdrsy daha farklı bir şeyler yapmak isterse bakabiliriz.
