### ISSUE TITLE
Altyapı

### ISSUE THREAD

**Issue by fatihmeh** [fatihmeh/Choose-Your-Operating-System#2]
Sitenin altyapısı Github Pages ile yapılacağını düşünerek html ve js kullanmak durumundayız. Detayları burada tartışabiliriz.

**Comment by obdegirmenci** [comment]
Tüm seçenekleri baştan sona JS ile oluşturup kontrollerini basit bir "if" düzeniyle mi sağlayalım yoksa soru ve ve olası cevapları HTML içerisinde, liste gibi yapılara mantıksal biçimde yerleştirip JS'yi bunların gösteriminde mi kullanalım? İkinci yöntem ile ayrılan yollar ve cevaplar listeler üzerinden belirlenirken birinci yöntemde oluşturma ve yönlendirme tamamen JS üzerinden olacak. İkinci yöntemde yapı bir kez kurulduğu zaman ekstra cevaplarla senaryoyu genişletmek ve farklı konulara uyarlamak daha kolay olur. Birincisinde kodu sürekli düzenlemek gerekir.

**Comment by fatihmeh** [comment]
Js ile seçimler sonrası girdilerden geleni toplayıp sonucu gösterebiliriz. Bir kere kuruncu düzeni sonrasında pek değiştirme isteğinde bulunmayız diye düşünüyorum.

**Comment by fatihmeh** [comment]
Seçimleri alabileceğimiz başka bir dosya yapma ihtimalimiz var mı? Json dosyasından filan çekme gibi.

**Comment by obdegirmenci** [comment]
Evet yapabiliriz. Kullanımı sanırım Array gibi olur.

**Comment by fatihmeh** [comment]
Json dosyası hazırlıyordum fakat bunu okumayı anlatmaya uğraşmak yerine direk koda seçenekleri yazmak daha efektif olabilir.

**Comment by obdegirmenci** [comment]
Son düzenlemede onun ufak bir örneğini yaptım. Sonuçları bu şekilde geliyor.
![resim](https://user-images.githubusercontent.com/22788481/59708926-6ac4f180-920e-11e9-9e55-d922a59d5016.png)

Direkt func dosyası içinde array olarak da kullanabiliriz ama böyle daha düzenli görünüyor. Hem ayrı dillerdeki versiyonunu hazırlerken kullanıcıya hepsini tek seferde yükletmek zorunda kalmayız.

**Comment by obdegirmenci** [comment]
Asıl kullanım şekline ait yapıyı oluşturmak için çalışmalara başladım. Tüm soruları, cevapları ve bunlarla ilgili tüm verileri alabiliyoruz. Sıra bu verileri döngü yerine sadece gerektiği zaman gösterebilmekte. Geçici olarak döngüyü iptal ettim ve seçtiğim bir adet sorunun görünmesini sağladım. Cevapları oluştururken de etkileşime geçmek için kullanmaı planladığım yeni etiket özelliklerini ekledim.

**Comment by obdegirmenci** [comment]
Asıl kullanım şekline ait yapıyı oluşturmak için çalışmalara başladım. Tüm soruları, cevapları ve bunlarla ilgili diğer verileri alabiliyoruz. Sıra bu verileri döngü yerine sadece gerektiği zaman gösterebilmekte. Geçici olarak döngüyü iptal ettim ve seçtiğim bir adet sorunun görünmesini sağladım. Elementleri oluştururken etkileşime geçmek için kullanmayı planladığım yeni etiket özelliklerini ekledim.

Attığın Mozilla sayfasını incelerken kullanımını görüp araştırdım. **HTML 5**'de etiketlere özel özellikler tanımlayabiliyormuşuz. Böylece `id` veya `class` kısmını gereksiz yere meşgul etmek zorunda kalmayacağız. Daha anlamlı ve erişmesi kolay isimler kullanabileceğiz.

![resim](https://user-images.githubusercontent.com/22788481/60712312-63485c80-9f1f-11e9-9c6a-313429c50c0e.png)

```
data-question
data-answer
data-go
```
Zaten daha önceden cevaplar başka soruya mı yoksa sonuca mı götürüyor ekrana yazdırmıştık. Eklediğim resim de de hâlâ yazıyor. Şimdi onun yerine bu değerleri **data-go** özelliğinin içine ekledim. Eğer birden fazla sonuç varsa da virgülle ayırmasını sağladım ki daha sonra kullanırken o değerleri ayrıştırıp kullanabilelim. Yoksa hepsini birleşik biçimde tutardı.

Sonrasında ufak bir deneme hazırladım. **data-answer** özelliğine ait tüm **li** etiketlerini seçtim. Bunlardan birisine tıklandığı zaman ilgili cevabın **data-go** değerini konsola yazdırdım.
![resim](https://user-images.githubusercontent.com/22788481/60712986-d56d7100-9f20-11e9-9ca7-bb6a80892d0e.png)

_Sonuç:_
![resim](https://user-images.githubusercontent.com/22788481/60713747-4f522a00-9f22-11e9-969a-4313fe82c81b.png)
Bunu mevcut soruyu silip, sonraki aşamaya geçerken kullanacağız.

**Comment by fatihmeh** [comment]
Geçen gün sorduğum şeyde aynı şekilde kullanım olduğunu gördüm.
![image](https://user-images.githubusercontent.com/34105974/60815268-f099e400-a19f-11e9-9fd6-2880a6a55b39.png)

**Comment by fatihmeh** [comment]
Kod aşamasını buradan devam ettirelim.

https://github.com/fatihmeh/Choose-Your-Operating-System/tree/branch-kod

**Comment by fatihmeh** [comment]
#9 ile beraber issue kapandı.
