### ISSUE TITLE
Yapılabilirler

### ISSUE THREAD

**Issue by fatihmeh** [fatihmeh/Choose-Your-Operating-System#3]
Dil seçeneği olabilir İngilizce ve Türkçe olarak. Akla gelen fikirleri buradan konuşabiliriz.

**Comment by obdegirmenci** [comment]
Duyarlı tasarım ile mobil cihazlara uyum sağlanabilir.

Ara sorular ilgili simgelerle desteklenebilir.
"Zengin misin? (Cüzdan simgesi)"

Varılan sonuca ait ürüne bağlantı verilebilir.

**Comment by fatihmeh** [comment]
Github pages ile arama motorlarına uyum sağlama imkanı varmış.
https://help.github.com/en/articles/sitemaps-for-github-pages
sitemap.xml oluşturabiliriz.

Google analytics kodu kullanma imkanı varmış.
https://github.com/jmcglone/jmcglone.github.io/blob/master/_includes/analytics.html

**Comment by fatihmeh** [comment]
Site tamamlanınca yenilikler için üzerinden gittiğimiz bir issue açarız.
