### ISSUE TITLE
Tasarım

### ISSUE THREAD

**Issue by fatihmeh** [fatihmeh/Choose-Your-Operating-System#5]
İlk tasarım için draft çalışma olarak şöyle bir şey yaptım. Arka plan ve soru olan kısım image şeklinde olabilir css ile kasmak yerine. Arka plan gradient yaptım ama transparency düşürmek gerek.
![image](https://user-images.githubusercontent.com/34105974/59739320-169d2a00-926d-11e9-853b-39eb38844f97.png)

**Comment by obdegirmenci** [comment]
Ben de tasarım yerleşimi hakkında böyle bir şema hazırladım. Görünümü temsil etmemektedir. :D

![resim](https://user-images.githubusercontent.com/22788481/59774107-8b955180-92b7-11e9-8385-cf6d1553f954.png)

**Comment by fatihmeh** [comment]
93 ylında html ilk kez tasarlanırken şablonlar ele geçirildi diye haber yapar bunu bizim teknoloji siteleri :D

**Comment by obdegirmenci** [comment]
>_İşte Ortaya Çıkan **BÜYÜK** GİZEM!_

>_Bu Teknolojinin Arkasında  Bakın **KİM** varmış!_

>_İnterneti **Biz** Tasarlamışız!_

**Comment by fatihmeh** [comment]
Tasarım aşamasını buradan devam ettirelim.
https://github.com/fatihmeh/Choose-Your-Operating-System/tree/branch-tasar%C4%B1m

**Comment by obdegirmenci** [comment]
Sorulara geçiş esnasında şöyle birşey düşünmüştüm ama teknik imkansızlıklar nedeniyle iptal etmek zorunda kaldım. :D
 ![2019-08-31 13-08-13](https://user-images.githubusercontent.com/22788481/64066248-d15b8800-cc1f-11e9-8ce6-20045c5a5d36.gif)

**Comment by obdegirmenci** [comment]
> Sorulara geçiş esnasında şöyle birşey düşünmüştüm ama teknik imkansızlıklar nedeniyle iptal etmek zorunda kaldım. :D

Yerine basit bir renk geçişi ekledim.
![2019-08-31 18-53-28](https://user-images.githubusercontent.com/22788481/64066359-28ae2800-cc21-11e9-8bc9-d94fc6263d41.gif)

**Comment by fatihmeh** [comment]
Baya profesyonel gözüküyor

**Comment by fatihmeh** [comment]
#10 ile kapatılacak eğer uygunsa @obdegirmenci
